### ISSUE TITLE
Emoji+ plugin issue

### ISSUE THREAD

**Issue by justinr25** [Garulf/Emoji-plus#14]
[2022-11-19.txt](https://github.com/Garulf/Emoji-plus/files/10048393/2022-11-19.txt)

Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 11/19/2022 22:29:17
Exception:
Emoji+ Exception: 
Websites: https://github.com/Garulf/emoji-plus
Author: Garulf
Version: 1.4.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Emoji+|Traceback (most recent call last):
  File "C:\Users\Justin\AppData\Roaming\FlowLauncher\Plugins\Emoji+-1.4.3\run.py", line 9, in <module>
    from plugin.emoji import Emoji
ModuleNotFoundError: No module named 'plugin.emoji'

 ---> System.IO.InvalidDataException: Emoji+|Traceback (most recent call last):
  File "C:\Users\Justin\AppData\Roaming\FlowLauncher\Plugins\Emoji+-1.4.3\run.py", line 9, in <module>
    from plugin.emoji import Emoji
ModuleNotFoundError: No module named 'plugin.emoji'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 626
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 627
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Hello @justinr25 thanks for reporting this issue.

Odd the error is indicating an issue with the plugin finding the rest of itself. Which Python are you using and which version?

Please try and uninstall and reinstall. If there really is a missing file it'll hopefully be corrected on reinstall.
