### ISSUE TITLE
Issue when activating EMOJI Plugin

### ISSUE THREAD

**Issue by alfredovaras** [Garulf/Emoji-plus#15]
Hi there,

I have been trying to use the Emoji Plug-in without success, I tried today once more and decided to send you the log file.

Hope you can help me.

[2023-01-18.txt](https://github.com/Garulf/Emoji-plus/files/10443963/2023-01-18.txt)

**Comment by Ryuo1** [comment]
Same issue.
Log: 
[2023-07-20.txt](https://github.com/Garulf/Emoji-plus/files/12105341/2023-07-20.txt)

**Comment by Garulf** [comment]
Looks like FLow Launcher is having trouble loading the plugin here:
`09:35:11.0188+01:00 - ERROR - PluginManager.InitializePluginsAsync - Fail to Init plugin: Emoji+`

Please try reinstalling the plugin and making sure its enabled in settings.

![image](https://github.com/Garulf/Emoji-plus/assets/535299/aec69f5d-5160-441b-a122-60e730bee70b)

**Comment by Ryuo1** [comment]
> Looks like FLow Launcher is having trouble loading the plugin here: `09:35:11.0188+01:00 - ERROR - PluginManager.InitializePluginsAsync - Fail to Init plugin: Emoji+`
> 
> Please try reinstalling the plugin and making sure its enabled in settings.
> 
> ![image](https://user-images.githubusercontent.com/535299/254926924-aec69f5d-5160-441b-a122-60e730bee70b.png)

I tried reinstalling and it failed the first two times. It successfully installed at the third attempt and so I enabled it in the settings.
so now when I open flow launcher and type emoji+ hotkey, flow launcher crashes.
```
Please open new issue in: https://github.com/Garulf/emoji-plus/issues
1. upload log file: C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.15.0\UserData\Logs\1.15.0\2023-07-20.txt
2. copy below exception message

Flow Launcher version: 1.15.0
OS Version: 23475.1000
IntPtr Length: 8
x64: True

Python Path: C:\Users\anshu\scoop\apps\python\3.11.3\pythonw.exe
Node Path: 
Date: 07/20/2023 21:19:35
Exception:
Emoji+ Exception: 
Websites: https://github.com/Garulf/emoji-plus
Author: Garulf
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.15.0\UserData\Plugins\Emoji+-2.0.0\run.py", line 9, in <module>
    from plugin.emoji import Emoji
  File "C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.15.0\UserData\Plugins\Emoji+-2.0.0\plugin\emoji.py", line 7, in <module>
    from flox import Flox, utils, ICON_BROWSER, ICON_COPY
  File "C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.15.0\UserData\Plugins\Emoji+-2.0.0\lib\flox\__init__.py", line 50, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.15.0\UserData\Plugins\Emoji+-2.0.0\run.py", line 9, in <module>
    from plugin.emoji import Emoji
  File "C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.15.0\UserData\Plugins\Emoji+-2.0.0\plugin\emoji.py", line 7, in <module>
    from flox import Flox, utils, ICON_BROWSER, ICON_COPY
  File "C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.15.0\UserData\Plugins\Emoji+-2.0.0\lib\flox\__init__.py", line 50, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 826
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 800
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
Logs:
[2023-07-20.txt](https://github.com/Garulf/Emoji-plus/files/12111613/2023-07-20.txt)

**Comment by Ryuo1** [comment]
Could this be an issue with scoop or some folder permissions error?

**Comment by Garulf** [comment]
No. My plugins are aware of scoop installations. 

It's odd because the code should have no trouble finding your install.

**Comment by Ryuo1** [comment]
Could it be an isssue with python?
