### ISSUE TITLE
Emoji+ Exception

### ISSUE THREAD

**Issue by SahaSG552** [Garulf/Emoji-plus#17]
[2023-06-20.txt](https://github.com/Garulf/Emoji-plus/files/11797114/2023-06-20.txt)

Flow Launcher version: 1.15.0
OS Version: 22621.1848
IntPtr Length: 8
x64: True

Python Path: C:\Users\sahas\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 06/20/2023 10:12:51
Exception:
Emoji+ Exception: 
Websites: https://github.com/Garulf/emoji-plus
Author: Garulf
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\sahas\AppData\Roaming\FlowLauncher\Plugins\Emoji+-2.0.0\run.py", line 9, in <module>
    from plugin.emoji import Emoji
  File "C:\Users\sahas\AppData\Roaming\FlowLauncher\Plugins\Emoji+-2.0.0\plugin\emoji.py", line 7, in <module>
    from flox import Flox, utils, ICON_BROWSER, ICON_COPY
  File "C:\Users\sahas\AppData\Roaming\FlowLauncher\Plugins\Emoji+-2.0.0\lib\flox\__init__.py", line 46, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\sahas\AppData\Roaming\FlowLauncher\Plugins\Emoji+-2.0.0\run.py", line 9, in <module>
    from plugin.emoji import Emoji
  File "C:\Users\sahas\AppData\Roaming\FlowLauncher\Plugins\Emoji+-2.0.0\plugin\emoji.py", line 7, in <module>
    from flox import Flox, utils, ICON_BROWSER, ICON_COPY
  File "C:\Users\sahas\AppData\Roaming\FlowLauncher\Plugins\Emoji+-2.0.0\lib\flox\__init__.py", line 46, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 826
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 800
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Strange it's saying it can not find your launcher and proceeds to correctly show the path of your launcher. 


Please try restarting Flow Launcher and see if it fixes your issue.
