### ISSUE TITLE
I think it's cus of a space between the username

### ISSUE THREAD

**Issue by theSoberSobber** [Garulf/Emoji-plus#21]
Please open new issue in: https://github.com/Garulf/emoji-plus/issues
1. upload log file: C:\Users\Pavit Chhabra\scoop\apps\Flow-Launcher\current\app-1.16.1\UserData\Logs\1.16.1\2023-08-22.txt
2. copy below exception message

Flow Launcher version: 1.16.1
OS Version: 22621.2134
IntPtr Length: 8
x64: True

Python Path: C:\Users\Pavit Chhabra\AppData\Local\Programs\Python\Python310\pythonw.exe
Node Path: C:\ProgramData\nvm\v20.3.1\node.exe
Date: 08/22/2023 01:50:22
Exception:
Emoji+ Exception: 
Websites: https://github.com/Garulf/emoji-plus
Author: Garulf
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\Pavit Chhabra\scoop\apps\Flow-Launcher\current\app-1.16.1\UserData\Plugins\Emoji+-2.0.0\run.py", line 9, in <module>
    from plugin.emoji import Emoji
  File "C:\Users\Pavit Chhabra\scoop\apps\Flow-Launcher\current\app-1.16.1\UserData\Plugins\Emoji+-2.0.0\plugin\emoji.py", line 7, in <module>
    from flox import Flox, utils, ICON_BROWSER, ICON_COPY
  File "C:\Users\Pavit Chhabra\scoop\apps\Flow-Launcher\current\app-1.16.1\UserData\Plugins\Emoji+-2.0.0\lib\flox\__init__.py", line 46, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\Pavit Chhabra\scoop\apps\Flow-Launcher\current\app-1.16.1\UserData\Plugins\Emoji+-2.0.0\run.py", line 9, in <module>
    from plugin.emoji import Emoji
  File "C:\Users\Pavit Chhabra\scoop\apps\Flow-Launcher\current\app-1.16.1\UserData\Plugins\Emoji+-2.0.0\plugin\emoji.py", line 7, in <module>
    from flox import Flox, utils, ICON_BROWSER, ICON_COPY
  File "C:\Users\Pavit Chhabra\scoop\apps\Flow-Launcher\current\app-1.16.1\UserData\Plugins\Emoji+-2.0.0\lib\flox\__init__.py", line 46, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Kickersatanist** [comment]
You can't name the folder anything other than "FlowLauncher", that's the problem I suppose
