### ISSUE TITLE
Fail to Init Plugins

### ISSUE THREAD

**Issue by AstudilloMarillo** [Garulf/Emoji-plus#22]
"Plugins: Emoji+ - fail to load and would be disabled, please contact plugin creator for help"

Emoji+ now suddenly refuses to even launch. Since a week now, I think. 
If I force it, it gives this error:

Flow Launcher version: 1.16.1
OS Version: 19045.3324
IntPtr Length: 8
x64: True

Python Path: C:\Users\[insert username]\AppData\Local\Programs\Python\Python38\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 09/22/2023 19:31:53
Exception:
Emoji+ Exception: 
Websites: https://github.com/Garulf/emoji-plus
Author: Garulf
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\[insert username]\AppData\Roaming\FlowLauncher\Plugins\Emoji+-2.0.0\run.py", line 9, in <module>
    from plugin.emoji import Emoji
  File "C:\Users\[insert username]\AppData\Roaming\FlowLauncher\Plugins\Emoji+-2.0.0\plugin\emoji.py", line 7, in <module>
    from flox import Flox, utils, ICON_BROWSER, ICON_COPY
  File "C:\Users\[insert username]\AppData\Roaming\FlowLauncher\Plugins\Emoji+-2.0.0\lib\flox\__init__.py", line 50, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\[insert username]\AppData\Roaming\FlowLauncher\Plugins\Emoji+-2.0.0\run.py", line 9, in <module>
    from plugin.emoji import Emoji
  File "C:\Users\[insert username]\AppData\Roaming\FlowLauncher\Plugins\Emoji+-2.0.0\plugin\emoji.py", line 7, in <module>
    from flox import Flox, utils, ICON_BROWSER, ICON_COPY
  File "C:\Users\[insert username]\AppData\Roaming\FlowLauncher\Plugins\Emoji+-2.0.0\lib\flox\__init__.py", line 50, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by AstudilloMarillo** [comment]
Okay, deleting the Settings.json file (located in %AppData%\FlowLauncher\Settings\Plugins\Emoji+) and restarting Flow Launcher seems to fix it.
